# Generated by Django 6.1 on 2026-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
